import { NextRequest, NextResponse } from 'next/server';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { db } from '@/lib/db'; import { requireUser } from '@/lib/auth'; import { error, forbidden, serverError, unauthorized } from '@/lib/http';
async function ensureCart(userId:string){const existing=await db.cart.findUnique({where:{userId}});if(existing)return existing;try{return await db.cart.create({data:{userId}})}catch(cause){if(cause instanceof Prisma.PrismaClientKnownRequestError&&cause.code==='P2002'){const raced=await db.cart.findUnique({where:{userId}});if(raced)return raced}throw cause}}
async function cartFor(userId:string){await ensureCart(userId);return db.cart.findUnique({where:{userId},include:{items:{include:{product:{include:{images:true,inventory:true}},variant:true}}}})}
export async function GET(){const user=await requireUser();if(!user)return unauthorized();try{return NextResponse.json({cart:await cartFor(user.id)})}catch(e){return serverError(e)}}
const addSchema=z.object({productId:z.string(),variantId:z.string().optional(),quantity:z.number().int().min(1).max(25).default(1),customization:z.record(z.string(),z.unknown()).optional()});
export async function POST(request:NextRequest){const user=await requireUser();if(!user)return unauthorized();try{const parsed=addSchema.safeParse(await request.json());if(!parsed.success)return error('Choose a product and valid quantity.');const d=parsed.data;const product=await db.product.findUnique({where:{id:d.productId},include:{variants:true,inventory:true}});if(!product||!product.published)return error('Product is no longer available.',404);if(product.variants.length&&!d.variantId)return error('Please choose a product option.');const variant=d.variantId?product.variants.find((v:any)=>v.id===d.variantId):null;if(d.variantId&&!variant)return error('That product option is unavailable.',404);const cart=await ensureCart(user.id);const existing=await db.cartItem.findFirst({where:{cartId:cart.id,productId:product.id,variantId:d.variantId??null}});const requestedQuantity=(existing?.quantity??0)+d.quantity;const stock=variant?.stock??product.inventory?.quantity??0;if(requestedQuantity>25)return error('You can add up to 25 of this piece to your bag.',409);if(stock<requestedQuantity)return error('There is not enough stock for that quantity.',409);if(existing)await db.cartItem.update({where:{id:existing.id},data:{quantity:requestedQuantity,customization:d.customization as any}});else await db.cartItem.create({data:{cartId:cart.id,productId:product.id,variantId:d.variantId??undefined,quantity:d.quantity,customization:d.customization as any}});return NextResponse.json({cart:await cartFor(user.id)});}catch(e){return serverError(e)}}
const edit=z.object({itemId:z.string(),quantity:z.number().int().min(0).max(25)});
export async function PATCH(request:NextRequest){const user=await requireUser();if(!user)return unauthorized();try{const parsed=edit.safeParse(await request.json());if(!parsed.success)return error();const cart=await db.cart.findUnique({where:{userId:user.id},include:{items:{include:{product:{include:{inventory:true}},variant:true}}}});const item=cart?.items.find((i:any)=>i.id===parsed.data.itemId);if(!item)return error('That cart item could not be found.',404);if(parsed.data.quantity===0)await db.cartItem.delete({where:{id:item.id}});else{const available=item.variant?.stock??item.product.inventory?.quantity??0;if(parsed.data.quantity>available)return error('There is not enough stock for that quantity.',409);await db.cartItem.update({where:{id:item.id},data:{quantity:parsed.data.quantity}})}return NextResponse.json({cart:await cartFor(user.id)});}catch(e){return serverError(e)}}
export async function DELETE(request:NextRequest){const user=await requireUser();if(!user)return unauthorized();try{const id=request.nextUrl.searchParams.get('itemId');if(!id)return error('Cart item is required.');await db.cartItem.deleteMany({where:{id,cart:{userId:user.id}}});return NextResponse.json({cart:await cartFor(user.id)});}catch(e){return serverError(e)}}
