import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@/lib/db';
import { requireAdmin } from '@/lib/auth';
import { error, forbidden, serverError } from '@/lib/http';
export async function GET(_: NextRequest, { params }: { params: { slug: string } }) { try { const product = await db.product.findUnique({ where: { slug: params.slug }, include: { images: { orderBy: { position: 'asc' } }, variants: true, category: true, inventory: true, reviews: { include: { user: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 30 } } }); if (!product || !product.published) return error('Product is no longer available.', 404); return NextResponse.json({ product }); } catch (e) { return serverError(e); } }
const update = z.object({ name:z.string().min(2).optional(), slug:z.string().regex(/^[a-z0-9-]+$/).optional(), description:z.string().min(1).optional(), price:z.number().int().nonnegative().optional(), compareAtPrice:z.number().int().nonnegative().nullable().optional(), sku:z.string().min(1).optional(), categoryId:z.string().nullable().optional(), material:z.string().nullable().optional(), color:z.string().nullable().optional(), size:z.string().nullable().optional(), published:z.boolean().optional(), featured:z.boolean().optional(), tags:z.array(z.string()).optional(), videoUrl:z.string().url().nullable().optional(), seoTitle:z.string().nullable().optional(), seoDescription:z.string().nullable().optional(), stock:z.number().int().nonnegative().optional() });
export async function PATCH(request: NextRequest,{params}:{params:{slug:string}}){if(!(await requireAdmin()))return forbidden();try{const data=update.safeParse(await request.json());if(!data.success)return error('Check the product details and try again.');const {stock,...fields}=data.data;const product=await db.$transaction(async (tx:any)=>{const p=await tx.product.update({where:{slug:params.slug},data:fields});if(stock!==undefined)await tx.inventory.upsert({where:{productId:p.id},create:{productId:p.id,quantity:stock},update:{quantity:stock}});return tx.product.findUnique({where:{id:p.id},include:{inventory:true,images:true,variants:true}})});return NextResponse.json({product});}catch(e){return serverError(e)}}
export async function DELETE(_:NextRequest,{params}:{params:{slug:string}}){if(!(await requireAdmin()))return forbidden();try{await db.product.delete({where:{slug:params.slug}});return NextResponse.json({ok:true});}catch(e){return serverError(e)}}
